### PR TITLE
Add check for existing files during install

### LINKED ISSUE #35: "update_template.sh install" Overwrites files
Running `. Dedman-Thesis-Latex-Template/update_template.sh install` after editing some of the files that are copied will sync those files back to the template and overwrite any of the user's changes. Examples of files this is likely to happen is `Dedman-Thesis-Latex-Template/latex/front_pages.tex`, `latex/user_config.tex`, and `user_thesis.tex`.

The most robust solution that should definitely be put in place is to have the installer check that the files exist before copying them over. Below are a few other suggestions that can also be considered.

It could be stressed that users should change the name of the template files to prevent overwriting files of the same name. An example where this already exists is in the Makefile there is an option to compile `$(USER)_thesis.tex` instead of `user_thesis.tex` that I had not been using. I have made this change now that this issue has happened to me. To facilitate the necessity of changing file names, the example files in the template could also have more generic names such as "temp_*". A good file name is the example bibliography `example.bib`. File names that aren't generic enough and are less likely to be changed are `Dedication.tex`, `Acknowledgements.tex`, `Abstract.tex`, `preface.tex`, `introduction.tex`, and `appendix_A.tex` all in `/src` .

Another personal lesson is that I will try to push all changes to git before I attempt any changes to the template files. Perhaps a warning could be issued whenever a command is run that notifies the user as to which files will be changed before the changes happen. This could be accompanied by a prompt to accept those changes.

### LINKED ISSUE #36: Move front_pages.tex out of Dedman-Thesis-Latex-Template
I think that `Dedman-Thesis-Latex-Template/latex/front_pages.tex` should be copied into the user's `/latex` directory.

This script requires changing the names of the dedication, acknowledgement, and abstract files and I don't think the user should have to make any modifications inside of `/Dedman-Thesis-Latex-Template`.

If this change is made, then line 18 of `user_thesis.tex` should correspondingly be changed from

`\input{Dedman-Thesis-Latex-Template/latex/front_pages.tex}`
to
`\input{/latex/front_pages.tex}`

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #35 and resolves #36

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@danjardin 

Can you put the following in a bash script and run it someplace on your machine (anywhere works) and give me your feedback?

```
#!/usr/bin/env bash

mkdir thesis_example
cd thesis_example
git init .
git submodule add https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template.git
cd Dedman-Thesis-Latex-Template
git checkout origin/revise/add-protection -b revise/add-protection
cd ..

mkdir latex
touch latex/user_commands.tex
mkdir src
touch src/abstract.tex

bash Dedman-Thesis-Latex-Template/update_template.sh install
make
```

**Comment by danjardin** [comment]
@matthewfeickert 

I don't know where you implemented this change, but it worked nicely the first time when starting from a clean slate. However, it overwrote my test files if I ran it a second time with `bash Dedman-Thesis-Latex-Template/update_template.sh install`.

I think your intention is that people only need to give the `install` command when first starting out, but it's reasonable for someone to think they need to re-install after pulling the latest version. Can you set it up to ask about possible overwrites every time?

It may be worth noting that giving `update` or no input did not overwrite anything; although I'm not sure what you mean by "base Latex files" with this: `Do you want to sync your base LaTeX files with the template? [Y/N]:` that comes up when you run the main function (aka no input). Are base Latex files the ones that control the build, or the user's files, or something else?

**Comment by danjardin** [comment]
Yes, this seems to work as originally expected. After installing the template, making the document, and installing again, it asks about whether you want to keep or overwrite a number of files:

- latex/user_commands.tex
- latex/user_packages.tex
- latex/metadata.tex
- src/abstract.tex
- src/acknowledgements.tex
- src/appendix_A.tex
- src/dedication.tex
- src/introduction.tex
- src/preface.tex
- src/user_config.tex
- Makefile

**Comment by danjardin** [comment]
One additional point:

When user_commands.tex and user_packages.tex were introduced, they were left out of files that were synced with the template. As such, a comment was added to the top of each file that they would not be overwritten, but I think that comment needs to be removed now because it seems that they could be overwritten and we don't want to provide a false sense of hope that they're immune.

**Comment by matthewfeickert** [comment]
> comment needs to be removed now because it seems that they could be overwritten and we don't want to provide a false sense of hope that they're immune.

To reach the level of protection that you're suggesting I think it makes more sense to just have 

```
bash Dedman-Thesis-Latex-Template/update_template.sh install
```

first do a check for _any_ existing files and then just throw a warning up and exit if they exist. This actually seems pretty reasonable, as this would have been the desired use case for when you ran `install` accidentally.

**Comment by matthewfeickert** [comment]
@danjardin This should now offer the level of safeguarding that we discussed (it now requires a manual override to install over a non-clean environment). Care to give feedback on the phrasing (run the script again)?

**Pull request merged**
